# Generated by Django 4.2.4 on 2023-08-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='stripe_id',
        ),
    ]
